name: Update Contribution Activity Graph

on:
  schedule:
    - cron: "17 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v6

      - name: Generate dark activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: dist/activity-graph-dark.svg
          options: theme=github-compact&hide_border=true&hide_title=true&bg_color=0D1117&color=8B949E&line=00C853&point=FFFFFF&area=true&area_color=00C853&radius=10&height=320&grid=true
      - name: Generate light activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: dist/activity-graph-light.svg
          options: theme=github-compact&hide_border=true&hide_title=true&bg_color=0D1117&color=8B949E&line=00C853&point=FFFFFF&area=true&area_color=00C853&radius=10&height=320&grid=true
      - name: Publish generated graphs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
